stages:
- test
- deploy

docker:test:
  stage: test
  tags:
    - docker
  image: php:8.0.1-fpm-buster
  before_script:
    - echo "Before Script"
  script:
    - echo "Script"

ssh:deploy:
  stage: deploy
  needs:
    - docker:test
  tags:
    - ssh
  script:
    - echo "Script"