name: "CI"
 
# Triggers the workflow on push or pull request events
on: [push, pull_request]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: '7.4'
            tools: phpstan, composer
      - name: Report PHP version
        run: php -v    
      - name: PHP Code Style (phpcs)
        uses: chindit/actions-phpcs@master
        with:
          # Folder to check code style
          dir: src/    
      - name: Get composer cache directory
        id: composercache
        run: echo "set-output"

      - name: Install dependencies
        run: composer install --prefer-dist
